name: "central-iam"
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
    paths: ["central-iam/**"]    
  pull_request:
    branches: ["main"]
    paths: ["central-iam/**"]    
jobs:
  run:
    name: "Workload Identity Job"
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Auth in GCP"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
      - name: "Terraform Init"
        working-directory: central-iam    
        run: terraform init
      - name: "Terraform Plan"
        working-directory: central-iam    
        run: terraform plan -out=plan.tfplan -input=false -lock-timeout=10m
      - name: "Terraform Apply"
        working-directory: central-iam    
        if: github.event_name == 'push'
        run: terraform apply -input=false -lock-timeout=10m plan.tfplan